# Script to produce bits/errno.h for NaCl.

# Copyright (C) 2015-2017 Free Software Foundation, Inc.
# This file is part of the GNU C Library.

# The GNU C Library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.

# The GNU C Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with the GNU C Library; if not, see
# <http://www.gnu.org/licenses/>.

BEGIN { maxerrno = 0 }

$1 == "#define" && $2 ~ /NACL_ABI_E[A-Z0-9_]+/ && $3 ~ /[0-9]+/ {
  ename = $2;
  sub(/NACL_ABI_/, "", ename);
  errno = $3 + 0;
  if (errno > maxerrno) maxerrno = errno;
  errnos[errno] = ename;
  errnos_by_name[ename] = errno;
  if ($4 == "/*" && !(ename in errno_text)) {
    etext = $5;
    for (i = 6; i <= NF && $i != "*/"; ++i)
      etext = etext " " $i;
    errno_text[ename] = etext;
  }
  next;
}

$1 == "@comment" && $2 == "errno.h" { errnoh=1; next }
errnoh == 1 && $1 == "@comment" {
  ++errnoh;
  etext = $3;
  for (i = 4; i <= NF; ++i)
    etext = etext " " $i;
  next;
}
errnoh == 2 && $1 == "@deftypevr" && $2 == "Macro" && $3 == "int" {
  ename = $4;
  errno_text[ename] = etext;
  next;
}

function define_errno(errno, ename) {
  etext = errno_text[ename];
  if (length(ename) < 8) ename = ename "\t";
  printf "#define\t%s\t%d\t/* %s */\n", ename, errno, etext;
}

END {
  print "\
/* This file generated by errnos.awk.  */\n\
\n\
#ifndef _BITS_ERRNO_H\n\
#define _BITS_ERRNO_H 1\n\
\n\
#if !defined _ERRNO_H && !defined _BITS_ERRNO_ENUM_H\n\
#error \"Never include <bits/errno.h> directly; use <errno.h> instead.\"\n\
#endif\n"

  for (i = 1; i <= maxerrno; ++i)
    if (i in errnos) define_errno(i, errnos[i]);

  print "\n\
#define	EWOULDBLOCK	EAGAIN\n\
#define	ENOTSUP		EOPNOTSUPP\n\
\n\
#undef __USE_TLS_ERRNO\n\
#define __USE_TLS_ERRNO 1\n\
\n\
#endif /* bits/errno.h.  */";
}
